package cn.com.cisec.cheyoumei.server.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * Comment generated by hbm2java
 */
@Entity
public class Comment implements Serializable {

	private int id;
	private Goods goodsId; //商品ID  
	private User user;//用户ID
	private int rasePoint;     //几个星(评论星级)
	private String message;    //评论信息
	private String remoteMac;  //远程的mac地址
	private String remoteIp;   //远程的ip地址
	private boolean isValid;   //评论是否有效(是否通过审核)
	private Date createdAt;    //评论的时间
	private Date updatedAt;    //更新的时间
	private Orders orders;     //订单关联
	
	public int getRasePoint() {
		return rasePoint;
	}
	public void setRasePoint(int rasePoint) {
		this.rasePoint = rasePoint;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	public Goods getGoodsId() {
		return goodsId;
	}
	public void setGoodsId(Goods goodsId) {
		this.goodsId = goodsId;
	}
	@ManyToOne(fetch=FetchType.LAZY)
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	@OneToOne(fetch=FetchType.LAZY)
	public Orders getOrders() {
		return orders;
	}
	public void setOrders(Orders orders) {
		this.orders = orders;
	}
	@Id
	@GeneratedValue
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getRemoteMac() {
		return remoteMac;
	}
	public void setRemoteMac(String remoteMac) {
		this.remoteMac = remoteMac;
	}
	public String getRemoteIp() {
		return remoteIp;
	}
	public void setRemoteIp(String remoteIp) {
		this.remoteIp = remoteIp;
	}
	public boolean isValid() {
		return isValid;
	}
	public void setValid(boolean isValid) {
		this.isValid = isValid;
	}
	public Date getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return updatedAt;
	}
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}
